export const types = {
    TYPE_UPDATE_MOVIE:"TYPE_UPDATE_MOVIE",
    TYPE_UPDATE_MOVIE_ARRAY:"TYPE_UPDATE_MOVIE_ARRAY",
    TYPE_UPDATE_CADEIRA:"TYPE_UPDATE_CADEIRA",
    TYPE_UPDATE_SALA_HORARIO:"TYPE_UPDATE_SALA",
    
}